import React from 'react';
import {
  View,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  Alert,
  Share,
} from 'react-native';
import { useRoute, useNavigation } from '@react-navigation/native';

interface RouteParams {
  payment: {
    id: string;
    amount: number;
    payment_type: string;
    payment_method: string | null;
    payment_period: string | null;
    status: string;
    due_date: string;
    paid_date: string | null;
    created_at: string;
    notes: string | null;
    transaction_id: string | null;
  };
  propertyName?: string;
  unitName?: string;
  tenantName?: string;
}

export default function PaymentReceiptScreen() {
  const navigation = useNavigation<any>();
  const route = useRoute();
  const { payment, propertyName, unitName, tenantName } = (route.params as RouteParams) || {};

  if (!payment) {
    return (
      <View style={styles.container}>
        <Text style={styles.errorText}>Receipt not found</Text>
      </View>
    );
  }

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  const formatPaymentMethod = (method: string | null) => {
    if (!method) return 'Not specified';
    return method
      .replace(/_/g, ' ')
      .replace(/\b\w/g, (l) => l.toUpperCase());
  };

  const formatPaymentType = (type: string) => {
    return type
      .replace(/_/g, ' ')
      .replace(/\b\w/g, (l) => l.toUpperCase());
  };

  const handleShare = async () => {
    try {
      const receiptText = `
PAYMENT RECEIPT
━━━━━━━━━━━━━━━━━━━━━━━━━

Receipt #: ${payment.id.substring(0, 8).toUpperCase()}
Date: ${formatDate(payment.paid_date || payment.created_at)}

${propertyName ? `Property: ${propertyName}` : ''}
${unitName ? `Unit: ${unitName}` : ''}
${tenantName ? `Tenant: ${tenantName}` : ''}

PAYMENT DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━
Amount: $${parseFloat(payment.amount.toString()).toFixed(2)}
Type: ${formatPaymentType(payment.payment_type)}
Method: ${formatPaymentMethod(payment.payment_method)}
${payment.payment_period ? `Period: ${payment.payment_period}` : ''}
Status: ${payment.status.toUpperCase()}

${payment.transaction_id ? `Transaction ID: ${payment.transaction_id}` : ''}
${payment.notes ? `Notes: ${payment.notes}` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Naya Property Management
      `.trim();

      await Share.share({
        message: receiptText,
        title: 'Payment Receipt',
      });
    } catch (error) {
      console.error('Share error:', error);
      Alert.alert('Error', 'Failed to share receipt');
    }
  };

  const getStatusColor = () => {
    switch (payment.status) {
      case 'completed':
        return '#34C759';
      case 'pending':
        return '#FF9500';
      case 'processing':
        return '#007AFF';
      case 'failed':
        return '#FF3B30';
      case 'refunded':
        return '#AF52DE';
      default:
        return '#8E8E93';
    }
  };

  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={styles.backButton}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Payment Receipt</Text>
        <TouchableOpacity onPress={handleShare}>
          <Text style={styles.shareButton}>Share</Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {/* Receipt Container */}
        <View style={styles.receiptCard}>
          {/* Logo/Header Section */}
          <View style={styles.receiptHeader}>
            <Text style={styles.receiptTitle}>PAYMENT RECEIPT</Text>
            <Text style={styles.receiptSubtitle}>Naya Property Management</Text>
          </View>

          {/* Receipt Number and Date */}
          <View style={styles.section}>
            <View style={styles.row}>
              <View style={styles.column}>
                <Text style={styles.label}>Receipt #</Text>
                <Text style={styles.receiptNumber}>
                  {payment.id.substring(0, 8).toUpperCase()}
                </Text>
              </View>
              <View style={styles.column}>
                <Text style={styles.label}>Date</Text>
                <Text style={styles.value}>
                  {formatDate(payment.paid_date || payment.created_at)}
                </Text>
              </View>
            </View>
          </View>

          {/* Property Information */}
          {(propertyName || unitName || tenantName) && (
            <>
              <View style={styles.divider} />
              <View style={styles.section}>
                <Text style={styles.sectionTitle}>PROPERTY INFORMATION</Text>
                {propertyName && (
                  <View style={styles.infoRow}>
                    <Text style={styles.infoLabel}>Property:</Text>
                    <Text style={styles.infoValue}>{propertyName}</Text>
                  </View>
                )}
                {unitName && (
                  <View style={styles.infoRow}>
                    <Text style={styles.infoLabel}>Unit:</Text>
                    <Text style={styles.infoValue}>{unitName}</Text>
                  </View>
                )}
                {tenantName && (
                  <View style={styles.infoRow}>
                    <Text style={styles.infoLabel}>Tenant:</Text>
                    <Text style={styles.infoValue}>{tenantName}</Text>
                  </View>
                )}
              </View>
            </>
          )}

          {/* Payment Details */}
          <View style={styles.divider} />
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>PAYMENT DETAILS</Text>

            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Type:</Text>
              <Text style={styles.infoValue}>{formatPaymentType(payment.payment_type)}</Text>
            </View>

            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Method:</Text>
              <Text style={styles.infoValue}>{formatPaymentMethod(payment.payment_method)}</Text>
            </View>

            {payment.payment_period && (
              <View style={styles.infoRow}>
                <Text style={styles.infoLabel}>Period:</Text>
                <Text style={styles.infoValue}>{payment.payment_period}</Text>
              </View>
            )}

            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Status:</Text>
              <View style={[styles.statusBadge, { backgroundColor: getStatusColor() + '22' }]}>
                <Text style={[styles.statusText, { color: getStatusColor() }]}>
                  {payment.status.toUpperCase()}
                </Text>
              </View>
            </View>

            {payment.transaction_id && (
              <View style={styles.infoRow}>
                <Text style={styles.infoLabel}>Transaction ID:</Text>
                <Text style={styles.infoValue}>{payment.transaction_id}</Text>
              </View>
            )}
          </View>

          {/* Amount Section */}
          <View style={styles.divider} />
          <View style={styles.amountSection}>
            <View style={styles.amountRow}>
              <Text style={styles.amountLabel}>Total Amount:</Text>
              <Text style={styles.amountValue}>
                ${parseFloat(payment.amount.toString()).toFixed(2)}
              </Text>
            </View>
          </View>

          {/* Notes */}
          {payment.notes && (
            <>
              <View style={styles.divider} />
              <View style={styles.section}>
                <Text style={styles.sectionTitle}>NOTES</Text>
                <Text style={styles.notesText}>{payment.notes}</Text>
              </View>
            </>
          )}

          {/* Footer */}
          <View style={styles.receiptFooter}>
            <Text style={styles.footerText}>
              This is an official receipt for your payment. Please keep this for your records.
            </Text>
            <Text style={styles.footerDate}>
              Generated on {new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
                hour: '2-digit',
                minute: '2-digit',
              })}
            </Text>
          </View>
        </View>

        {/* Action Buttons */}
        <View style={styles.actionButtons}>
          <TouchableOpacity style={styles.primaryButton} onPress={handleShare}>
            <Text style={styles.primaryButtonText}>📤 Share Receipt</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.secondaryButton}
            onPress={() => navigation.goBack()}
          >
            <Text style={styles.secondaryButtonText}>Close</Text>
          </TouchableOpacity>
        </View>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 16,
    paddingTop: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  backButton: {
    fontSize: 16,
    color: '#007AFF',
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000',
  },
  shareButton: {
    fontSize: 16,
    color: '#007AFF',
    fontWeight: '600',
  },
  content: {
    flex: 1,
    padding: 16,
  },
  receiptCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  receiptHeader: {
    alignItems: 'center',
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#007AFF',
  },
  receiptTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#000',
    marginBottom: 4,
    letterSpacing: 1,
  },
  receiptSubtitle: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  section: {
    marginVertical: 16,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#007AFF',
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  column: {
    flex: 1,
  },
  label: {
    fontSize: 12,
    color: '#999',
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  receiptNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000',
    fontFamily: 'monospace',
  },
  value: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginVertical: 16,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
    flex: 1,
  },
  infoValue: {
    fontSize: 14,
    color: '#000',
    fontWeight: '600',
    flex: 2,
    textAlign: 'right',
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  amountSection: {
    backgroundColor: '#F0F9FF',
    padding: 16,
    borderRadius: 8,
    marginVertical: 8,
  },
  amountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  amountLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: '#007AFF',
  },
  amountValue: {
    fontSize: 28,
    fontWeight: '700',
    color: '#007AFF',
  },
  notesText: {
    fontSize: 14,
    color: '#333',
    lineHeight: 20,
    fontStyle: 'italic',
  },
  receiptFooter: {
    marginTop: 24,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  footerText: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 8,
  },
  footerDate: {
    fontSize: 10,
    color: '#999',
    textAlign: 'center',
  },
  actionButtons: {
    marginTop: 16,
    gap: 12,
  },
  primaryButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  secondaryButton: {
    backgroundColor: '#f5f5f5',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#007AFF',
  },
  errorText: {
    fontSize: 16,
    color: '#d32f2f',
    textAlign: 'center',
    marginTop: 40,
  },
});
